version: 1.0.{build}
image: Visual Studio 2019
skip_branch_with_pr: true
branches:
  only:
    - master
skip_commits:
  files:
  - '**/*.md'
platform: Any CPU

build:
  project: '\src\LibBase.sln'
  publish_nuget: true
  parallel: true
  verbosity: normal
build_script:
  - dotnet build src/LibBase.sln -c Release
artifacts:
  - path: 'src\LibBase\bin\Release\*.nupkg'
    name: NuGet Package (Release)
deploy:
  provider: NuGet
  api_key:
    secure: jRFEcQuIP0Rmqjrxk1uX7lNkVxROi8MzMJ+KUUUR+1XyAbWviTaUAPvYZ9FyZC5K
  skip_symbols: true
  artifact: /.*\.nupkg/